version: '3.8'

services:
  # =========================================
  # Django Bootcamp
  # =========================================
  django:
    image: fjbardelli/dj_bootcamp
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 512M
      # update_config:
      #   parallelism: 1
      #   delay: 10s
        #failure_action: rollback
        #order: start-first
    networks:
      - appnet
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "https://dj-codigo-facilito.fliabardelli.com.ar/health/"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 30s
    environment:
      # Configuracion del Proxy & Certificados SSL 
      - VIRTUAL_HOST=dj-codigo-facilito.fliabardelli.com.ar
      - LETSENCRYPT_HOST=dj-codigo-facilito.fliabardelli.com.ar 
      - LETSENCRYPT_EMAIL=fernando@fliabardelli.com.ar
      - VIRTUAL_PORT=8000
      
networks:
  appnet:
    external: true