# Generated by Django 5.2.1 on 2025-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alumno_user_docente_user_coordinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('coordinador', 'Coordinador')], default='alumno', max_length=20),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('coordinador', 'Coordinador')], default='alumno', max_length=20),
        ),
        migrations.AddField(
            model_name='docente',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('coordinador', 'Coordinador')], default='alumno', max_length=20),
        ),
    ]
