# Generated by Django 5.2.4 on 2025-07-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alumno_rol_coordinador_rol_docente_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={},
        ),
    ]
