# Generated by Django 5.2.1 on 2025-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
