# Generated by Django 5.2.1 on 2025-06-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
        ('personas', '0003_alumno_rol_coordinador_rol_docente_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comisiones', to='personas.alumno')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='comisiones.comision')),
            ],
            options={
                'verbose_name': 'Comisión Alumno',
                'verbose_name_plural': 'Comisiones Alumnos',
                'ordering': ['comision', 'alumno'],
            },
        ),
    ]
