# Generated by Django 5.2.1 on 2025-06-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comisiones', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='comisiones.comision')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='examenes', to='personas.docente')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=0, max_digits=3)),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='personas.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='examenes.examen')),
            ],
        ),
    ]
