# Generated by Django 5.2.1 on 2025-06-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='examen',
            name='comision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='comisiones.comision'),
        ),
    ]
