# Generated by Django 5.2.1 on 2025-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_remove_examen_docente_remove_examen_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexamen',
            name='nota',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
