# Generated by Django 5.2.4 on 2025-07-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0003_alter_comision_docente_alter_comision_materia'),
        ('examenes', '0003_alter_resultadoexamen_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='comision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exa_comision', to='comisiones.comision'),
        ),
        migrations.DeleteModel(
            name='ResultadoExamen',
        ),
    ]
