name: Test, Build & Deploy to Portainer (Git Stack)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  PORTAINER_ENVIRONMENT_ID: 1

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List files for debug
        run: |
          pwd
          ls -R

      - name: Run Django Tests
        run: python bootcamp/bootcamp/manage.py test --keepdb
        #
        #  DJANGO_SETTINGS_MODULE: bootcamp.settings
        #  SECRET_KEY: dummy-secret-for-testing
        #  DEBUG: "False"

  build-and-deploy:
    name: Build Docker and Deploy to Portainer
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
        
      - name: Push Docker Image
        run: docker push $IMAGE_NAME:latest
        
      - name: ReDeploy to Portainer
        uses: spawnlab-dev/stack-deploy-action@v1
        with:
          host: ${{ secrets.PORTAINER_URL}}
          api-token: ${{ secrets.PORTAINER_TOKEN }}
          #swarmId: 'mtoqjoa2xxvXXXrw'
          endPointId: 1
          stack: ${{ secrets.PORTAINET_STACK_NAME }}
          client: 'portainer'
          action: 'deploy'
          compose: 'swarm.yml'
